[CmdletBinding()]param([string]$Source=(Split-Path $PSScriptRoot -Parent))
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$Source=[IO.Path]::GetFullPath($Source)
$temp=Join-Path ([IO.Path]::GetTempPath()) ('frontier-install-test-'+[guid]::NewGuid().ToString('N'));$passes=[Collections.Generic.List[string]]::new()
function Assert([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Digest([string]$Root){$rows=@(Get-ChildItem -LiteralPath $Root -File -Recurse|Sort-Object FullName|ForEach-Object {([IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/'))+'|'+$_.Length+'|'+(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash});$bytes=[Text.Encoding]::UTF8.GetBytes([string]::Join([Environment]::NewLine,$rows));$sha=[Security.Cryptography.SHA256]::Create();try{[Convert]::ToHexString($sha.ComputeHash($bytes))}finally{$sha.Dispose()}}
function Target([string]$Path){$i=Get-Item -LiteralPath $Path -Force;$t=[string](@($i.Target)[0]);if(-not[IO.Path]::IsPathRooted($t)){$t=Join-Path $i.Parent.FullName $t};[IO.Path]::GetFullPath($t).TrimEnd([char[]]'\/')}
function AddLinks([string]$Root,[string]$TargetSkills){[IO.Directory]::CreateDirectory($Root)|Out-Null;foreach($s in @(Get-ChildItem -LiteralPath (Join-Path $Source 'skills') -Directory|Sort-Object Name)){New-Item -ItemType Junction -Path (Join-Path $Root $s.Name) -Target (Join-Path $TargetSkills $s.Name)|Out-Null}}
function AssertMaterialized([string]$UserRoot,[string]$VersionRoot){
  $dirs=@(Get-ChildItem -LiteralPath $UserRoot -Directory -Force|Where-Object {$_.Name-notlike'.frontier-loop-*'}|Sort-Object Name);Assert ($dirs.Count-eq23) 'materialized skill count mismatch'
  foreach($d in $dirs){Assert (($d.Attributes-band[IO.FileAttributes]::ReparsePoint)-eq0) "installed skill is still a reparse point: $($d.Name)";Assert ((Digest $d.FullName)-eq(Digest (Join-Path $VersionRoot $d.Name))) "materialized skill bytes differ: $($d.Name)"}
}
function RemoveTree([string]$Root){if(-not(Test-Path -LiteralPath $Root)){return};$dirs=@(Get-ChildItem -LiteralPath $Root -Directory -Force -Recurse|Sort-Object {$_.FullName.Length} -Descending);foreach($d in $dirs){if(($d.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){Remove-Item -LiteralPath $d.FullName -Force}};[IO.Directory]::Delete($Root,$true)}
try{
 [IO.Directory]::CreateDirectory($temp)|Out-Null;$verify=Join-Path $Source 'scripts\Verify-FrontierLoop.ps1';$install=Join-Path $Source 'scripts\Install-FrontierLoop.ps1';$build=Join-Path $Source 'scripts\build_release.py'
 & $verify -Root $Source|Out-Null;Assert ($LASTEXITCODE-eq0) 'source verify failed';$passes.Add('verify-source')
 & python $build --self-test --test-temp-root $temp|Out-Null;Assert ($LASTEXITCODE-eq0) 'release self-test failed';$zip=Join-Path $temp 'release.zip';& python $build --root $Source --output $zip|Out-Null;Assert ($LASTEXITCODE-eq0) 'release build failed';& python $build --root $Source --output $zip --verify|Out-Null;Assert ($LASTEXITCODE-eq0) 'release byte verify failed';$passes.Add('deterministic-release')

 $destRoot=Join-Path $temp 'versions';$user=Join-Path $temp 'skills';$wi=(& $install -Source $Source -DestinationRoot $destRoot -UserSkillRoot $user -WhatIf|Out-String|ConvertFrom-Json);Assert ($wi.userSkillInstallMode-eq'materialized-copy') 'WhatIf install mode mismatch';Assert (-not(Test-Path -LiteralPath $destRoot)) 'WhatIf mutated destination';Assert (-not(Test-Path -LiteralPath $user)) 'WhatIf mutated skills';$passes.Add('what-if')
 $result=(& $install -Source $Source -DestinationRoot $destRoot -UserSkillRoot $user|Out-String|ConvertFrom-Json);$version=[string]((Get-Content -LiteralPath (Join-Path $Source '.codex-plugin\plugin.json')-Raw|ConvertFrom-Json).version);$dest=Join-Path $destRoot $version;Assert ($result.userSkillInstallMode-eq'materialized-copy') 'install mode mismatch';Assert (Test-Path -LiteralPath $dest -PathType Container) 'install missing destination';AssertMaterialized $user (Join-Path $dest 'skills');$passes.Add('install-materialized')
 & $install -Source $Source -DestinationRoot $destRoot -UserSkillRoot $user|Out-Null;Assert ($LASTEXITCODE-eq0) 'idempotent install failed';AssertMaterialized $user (Join-Path $dest 'skills');$passes.Add('idempotent')
 $doctrineViaCore=Join-Path $user 'frontier-core\references\ENGINEERING_JUDGMENT.md';Assert (Test-Path -LiteralPath $doctrineViaCore -PathType Leaf) 'core doctrine is not reachable from materialized install';foreach($name in @('frontier-architecture','frontier-debug-investigation','frontier-performance-engineering','frontier-migration')){$viaSibling=Join-Path $user ($name+'\..\frontier-core\references\ENGINEERING_JUDGMENT.md');Assert (Test-Path -LiteralPath $viaSibling -PathType Leaf) "doctrine is not reachable from materialized skill: $name"};$passes.Add('materialized-doctrine-resolution')

 [IO.File]::WriteAllText((Join-Path $dest 'tamper.txt'),'x');& $verify -Root $dest -ExpectedSource $Source 2>$null|Out-Null;Assert ($LASTEXITCODE-ne0) 'tamper was not detected';[IO.File]::Delete((Join-Path $dest 'tamper.txt'));$passes.Add('tamper-detection')
 $marketRoot=Join-Path $temp 'market-root';$marketDir=Join-Path $marketRoot '.agents\plugins';[IO.Directory]::CreateDirectory($marketDir)|Out-Null;$market=Join-Path $marketDir 'marketplace.json';[IO.File]::WriteAllText($market,'{"plugins":[{"name":"frontier-loop"},{"name":"frontier-loop"}]}');$dupFailed=$false;try{& $install -Source $Source -DestinationRoot (Join-Path $temp 'duplicate-dest') -MarketplaceFiles $market -WhatIf|Out-Null}catch{$dupFailed=$true};Assert $dupFailed 'duplicate marketplace was accepted';Assert (-not(Test-Path -LiteralPath (Join-Path $temp 'duplicate-dest'))) 'duplicate check mutated';$passes.Add('duplicate-marketplace')
 $marketGood=Join-Path $marketDir 'marketplace-good.json';$relative='./'+[IO.Path]::GetRelativePath($marketRoot,$Source).Replace('\','/');@{plugins=@(@{name='frontier-loop';source=@{source='local';path=$relative}})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $marketGood -Encoding utf8;& $install -Source $Source -DestinationRoot (Join-Path $temp 'marketplace-good-dest') -MarketplaceFiles $marketGood -WhatIf|Out-Null;Assert ($LASTEXITCODE-eq0) 'canonical marketplace source was rejected';$passes.Add('marketplace-canonical-source')
 $marketBad=Join-Path $marketDir 'marketplace-bad.json';@{plugins=@(@{name='frontier-loop';source=@{source='local';path='./wrong-source'}})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $marketBad -Encoding utf8;$badFailed=$false;try{& $install -Source $Source -DestinationRoot (Join-Path $temp 'marketplace-bad-dest') -MarketplaceFiles $marketBad -WhatIf|Out-Null}catch{$badFailed=$true};Assert $badFailed 'wrong marketplace source was accepted';$passes.Add('marketplace-wrong-source-fail-closed')

 $srcCase=Join-Path $temp 'source-junction-topology';$srcDest=Join-Path $srcCase 'versions';$srcUser=Join-Path $srcCase 'skills';AddLinks $srcUser (Join-Path $Source 'skills');$beforeTargets=@(Get-ChildItem -LiteralPath $srcUser -Directory|ForEach-Object {Target $_.FullName});$swi=(& $install -Source $Source -DestinationRoot $srcDest -UserSkillRoot $srcUser -WhatIf|Out-String|ConvertFrom-Json);Assert (@($swi.skillActions|Where-Object action -ne 'materialize-managed-junction').Count-eq0) 'source junction WhatIf action mismatch';Assert (-not(Test-Path -LiteralPath $srcDest)) 'source junction WhatIf mutated destination';Assert (@(Get-ChildItem -LiteralPath $srcUser -Directory|ForEach-Object {Target $_.FullName}|Where-Object {$_ -notin $beforeTargets}).Count-eq0) 'source junction WhatIf changed links';$passes.Add('source-junction-what-if')
 $si=(& $install -Source $Source -DestinationRoot $srcDest -UserSkillRoot $srcUser|Out-String|ConvertFrom-Json);$srcFinal=Join-Path $srcDest $version;Assert (@($si.skillActions|Where-Object action -ne 'materialize-managed-junction').Count-eq0) 'source junction install action mismatch';AssertMaterialized $srcUser (Join-Path $srcFinal 'skills');$passes.Add('source-junction-materialized')

 $rollbackCase=Join-Path $temp 'junction-rollback';$rollbackDest=Join-Path $rollbackCase 'versions';$rollbackUser=Join-Path $rollbackCase 'skills';AddLinks $rollbackUser (Join-Path $Source 'skills');$rollbackTargets=@{};foreach($l in @(Get-ChildItem -LiteralPath $rollbackUser -Directory)){$rollbackTargets[$l.Name]=Target $l.FullName};$failed=$false;try{& $install -Source $Source -DestinationRoot $rollbackDest -UserSkillRoot $rollbackUser -InjectFailureAfterSwap|Out-Null}catch{$failed=$true};Assert $failed 'junction injected failure did not fail';foreach($l in @(Get-ChildItem -LiteralPath $rollbackUser -Directory)){Assert ($l.LinkType-eq'Junction') "junction rollback did not restore link: $($l.Name)";Assert ((Target $l.FullName)-eq$rollbackTargets[$l.Name]) "junction rollback target mismatch: $($l.Name)"};Assert (-not(Test-Path -LiteralPath (Join-Path $rollbackDest $version))) 'junction rollback left destination';$passes.Add('junction-rollback')

 $priorCase=Join-Path $temp 'prior-junction-topology';$priorDest=Join-Path $priorCase 'versions';$priorSkills=Join-Path $priorDest '0.5.0\skills';[IO.Directory]::CreateDirectory($priorSkills)|Out-Null;foreach($s in @(Get-ChildItem -LiteralPath (Join-Path $Source 'skills') -Directory)){[IO.Directory]::CreateDirectory((Join-Path $priorSkills $s.Name))|Out-Null};$priorUser=Join-Path $priorCase 'skills';AddLinks $priorUser $priorSkills;$pi=(& $install -Source $Source -DestinationRoot $priorDest -UserSkillRoot $priorUser|Out-String|ConvertFrom-Json);Assert (@($pi.skillActions|Where-Object action -ne 'materialize-managed-junction').Count-eq0) 'prior junction install action mismatch';$priorFinal=Join-Path $priorDest $version;AssertMaterialized $priorUser (Join-Path $priorFinal 'skills');$passes.Add('prior-junction-materialized')

 $managedCase=Join-Path $temp 'prior-materialized-topology';$managedDest=Join-Path $managedCase 'versions';$managedPrior=Join-Path $managedDest '0.5.0\skills';$managedUser=Join-Path $managedCase 'skills';[IO.Directory]::CreateDirectory($managedPrior)|Out-Null;[IO.Directory]::CreateDirectory($managedUser)|Out-Null;foreach($s in @(Get-ChildItem -LiteralPath (Join-Path $Source 'skills') -Directory)){Copy-Item -LiteralPath $s.FullName -Destination (Join-Path $managedPrior $s.Name) -Recurse;[IO.File]::WriteAllText((Join-Path $managedPrior "$($s.Name)\prior-version.marker"),'0.5.0');Copy-Item -LiteralPath (Join-Path $managedPrior $s.Name) -Destination (Join-Path $managedUser $s.Name) -Recurse};$mi=(& $install -Source $Source -DestinationRoot $managedDest -UserSkillRoot $managedUser|Out-String|ConvertFrom-Json);Assert (@($mi.skillActions|Where-Object action -ne 'upgrade-materialized-version').Count-eq0) 'prior materialized upgrade action mismatch';$managedFinal=Join-Path $managedDest $version;AssertMaterialized $managedUser (Join-Path $managedFinal 'skills');Assert (@(Get-ChildItem $managedUser -Recurse -File -Filter 'prior-version.marker').Count-eq0) 'prior materialized marker survived upgrade';$passes.Add('prior-materialized-upgrade')

 $emptyCase=Join-Path $temp 'empty-rollback';$emptyDest=Join-Path $emptyCase 'versions';$emptyUser=Join-Path $emptyCase 'skills';[IO.Directory]::CreateDirectory($emptyUser)|Out-Null;foreach($s in @(Get-ChildItem -LiteralPath (Join-Path $Source 'skills') -Directory)){[IO.Directory]::CreateDirectory((Join-Path $emptyUser $s.Name))|Out-Null};$failed=$false;try{& $install -Source $Source -DestinationRoot $emptyDest -UserSkillRoot $emptyUser -InjectFailureAfterSwap|Out-Null}catch{$failed=$true};Assert $failed 'empty-directory injected failure did not fail';foreach($d in @(Get-ChildItem $emptyUser -Directory)){Assert (($d.Attributes-band[IO.FileAttributes]::ReparsePoint)-eq0) 'empty rollback produced reparse';Assert (@(Get-ChildItem $d.FullName -Force).Count-eq0) "empty rollback did not restore empty directory: $($d.Name)"};$passes.Add('directory-rollback')

 $wrongCase=Join-Path $temp 'wrong-topology';$wrongUser=Join-Path $wrongCase 'skills';$wrongTarget=Join-Path $wrongCase 'arbitrary';[IO.Directory]::CreateDirectory($wrongTarget)|Out-Null;[IO.Directory]::CreateDirectory($wrongUser)|Out-Null;New-Item -ItemType Junction -Path (Join-Path $wrongUser 'frontier-core') -Target $wrongTarget|Out-Null;$wrongDest=Join-Path $wrongCase 'versions';$failed=$false;try{& $install -Source $Source -DestinationRoot $wrongDest -UserSkillRoot $wrongUser -WhatIf|Out-Null}catch{$failed=$true};Assert $failed 'wrong arbitrary junction was accepted';Assert ((Target (Join-Path $wrongUser 'frontier-core'))-eq([IO.Path]::GetFullPath($wrongTarget))) 'wrong junction was mutated';Assert (-not(Test-Path -LiteralPath $wrongDest)) 'wrong junction failure mutated destination';$passes.Add('wrong-junction-fail-closed')
 $conflictCase=Join-Path $temp 'conflicting-materialized';$conflictUser=Join-Path $conflictCase 'skills';[IO.Directory]::CreateDirectory((Join-Path $conflictUser 'frontier-core'))|Out-Null;[IO.File]::WriteAllText((Join-Path $conflictUser 'frontier-core\foreign.txt'),'foreign');$failed=$false;try{& $install -Source $Source -DestinationRoot (Join-Path $conflictCase 'versions') -UserSkillRoot $conflictUser -WhatIf|Out-Null}catch{$failed=$true};Assert $failed 'foreign materialized directory was accepted';Assert (Test-Path (Join-Path $conflictUser 'frontier-core\foreign.txt')) 'foreign materialized directory was mutated';$passes.Add('foreign-directory-fail-closed')

 $residue=@(Get-ChildItem -LiteralPath $temp -Force -Recurse|Where-Object {$_.Name-like'.frontier-loop-*'});Assert ($residue.Count-eq0) 'transaction residue remains';$passes.Add('no-residue')
 [ordered]@{success=$true;tests=$passes;count=$passes.Count}|ConvertTo-Json -Compress;exit 0
}catch{[Console]::Error.WriteLine($_.Exception.Message);exit 1}finally{if(Test-Path -LiteralPath $temp){RemoveTree $temp}}
